### ISSUE TITLE
odd n's RP phase have lower symmetry I4mm instead of I4/mmm

### ISSUE THREAD

**Issue by prakayastha** [NU-CEM/rp_generator#1] opened 2024-03-15 14:11 UTC
I've been playing around with this script today and the script seems to work nicely to generate the n=1 I4/mmm RP phase. However, when I generate a larger n RP phase, the structures are in a lower symmetry phase -- I4mm. I've only seen this for the odd RP phases, script works nicely when n=even layers!

**Comment by lucydot** [comment] 2024-03-19 16:43
Hi @prakayastha  - we discussed this early but repeating conversation so that there is written record :)

It may be that enforcing symmetry, as you did, during relaxation did not allow for the expected structure to be found. It would be interesting to know if you can find expected structure when not enforcing symmetry. It would also be useful to know how you are detecting the space group (spglib?) and what the symmetry tolerance is (`symprec` in `spglib.spacegroup.get_spacegroup`) as it might be lower symmetry due to very slight displacements/noise.

**Comment by lucydot** [comment] 2024-03-19 16:44
I'm not going to close this as I would like to get to root of problem.

**Comment by lucydot** [comment] 2024-03-25 12:53
Hi @prakayastha  - I've just relaxed the Ba3Zr2S7 and Ba4Zr3S10 systems generated with RP_generator (the final structures are `./data/relaxed_22_RP` and `./data/relaxed_33_RP`). I've used FHI-aims and have not enforced any type of symmetry. 

I've used ASE to get space group (see `./scripts/cif_sym`), and it gives me I4/mmm for both which is what is expected. So I think the problem with your results might be linked to i) enforcing symmetry during relaxation; ii) sym_prec tag being very tight (I used `sym_prec=1e-5`). I've updated README to make clear not to enforce symmetry. 

I'm closing this issue as resolved as I cannot reproduce error when following the (now updated) guidance.

**Closed as completed** 2024-03-25 12:53 UTC
